package io.privatekb.ingestion.internal.domain;

public enum IndexingErrorCode {
    OLLAMA_NOT_RUNNING,
    EMBEDDING_MODEL_NOT_AVAILABLE,
    EMBEDDING_MODEL_INCOMPATIBLE,
    EMBEDDING_REQUEST_FAILED,
    EXTRACTED_CONTENT_MISSING,
    PROCESS_INTERRUPTED,
    CHECKPOINT_EXPIRED,
    INDEXING_INTERNAL_ERROR
}
